### ISSUE TITLE
question about training on jester dataset 

### ISSUE THREAD

**Issue by kinfeparty** [okankop/Efficient-3DCNNs#23]
Hello! I find the project from https://github.com/ahmetgunduz/Real-time-GesRec.        And I find that the model must pretrain on jester dataset and refine on egogesture dataset. The training code is the same as your code. So I want to use resnext101 to pretrain on jester dataset.The original code is suitable for mobilenet, and can run well, so I do the modification but got the bug. Here is my run-jester.sh 

python main.py --root_path /Lun4/fdh/Real-time-GesRec \
	--video_path ../jester-dataset/20bn-jester-v1 \
	--annotation_path annotation_Jester/jester.json \
	--result_path  results \
	--dataset jester \
	--n_classes 27 \
	--width_mult 2 \
	--n_finetune_classes 27 \
	--model resnext \
	--model_depth 101 \
	--resnet_shortcut B \
	--train_crop random \
	--learning_rate 0.01 \
	--sample_duration 32 \
	--modality RGB  \
	--downsample 1 \
	--batch_size 48 \
	--n_threads 16 \
	--checkpoint 1 \
	--n_val_samples 1 \
	--test \
	--n_epochs 100 \
	--ft_portion complete \

I found that this code can run on egogesture dataset ,but on jester dataset. I got a bug.

  File "/Lun4/fdh/Real-time-GesRec/train.py", line 30, in train_epoch
    outputs = model(inputs)
  File "/home/great57/.conda/envs/fdh/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/great57/.conda/envs/fdh/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 146, in forward
    "them on device: {}".format(self.src_device_obj, t.device))
RuntimeError: module must have its parameters and buffers on device cuda:0 (device_ids[0]) but found one of them on device: cpu

Can you help me fix it? Thank you!

**Comment by kinfeparty** [comment]
I add model=model.cuda() on train.py and the code works. It's  stange  that the original can works before on egogesture dataset

**Comment by okankop** [comment]
you can also use the pretrained models uploaded here https://drive.google.com/open?id=1eggpkmy_zjb62Xra6kQviLa67vzP_FR8

I am closing the issue since it is resolved.
