### ISSUE TITLE
Jester Pretrained model loading

### ISSUE THREAD

**Issue by ahkarami** [okankop/Efficient-3DCNNs#25]
Dear @okankop,
For the pretrained Jester models, I must use the **BGR** images/frames of range [0, 255] and with the below mean & std normalization (_i.e.,_ **Kinetics** mean)?   
`mean=[110.63666788, 103.16065604, 96.29023126], std=[1, 1, 1]`

**Comment by okankop** [comment]
Yes you are right

**Comment by ahkarami** [comment]
Thanks

**Comment by Marshall0304** [comment]
> Thanks

Hi buddy, did you inference with the pretrained model on jester dataset successfully? I use the BGR format input and the mean and std is as you said, but whatever the input is, the top 5 pred label is always: 1,16,24,5,26, the video is always classified to "doing other things", do you know the reason? Thanks
