### ISSUE TITLE
Path of dataset

### ISSUE THREAD

**Issue by changxinC** [okankop/Efficient-3DCNNs#27]
Can you provide a storage path for dataset?
such as:
data
├── classname1
│   ├── videoname1
│   │      ├── 0001.jpg
│   │      └── 0002.jpg
│   └── n_frames
├── classname2
│   ├── videoname2
│   │      ├── 0001.jpg
│   │      └── 0002.jpg
│   ├── videoname3
│   │      ├── 0001.jpg
│   │      └── 0002.jpg
│   └── n_frames

but it's not correct, I don't know how to set.

**Comment by pike-msonda** [comment]
Execute the number of frames script in utils folder for every corresponding dataset as follows.

`python utils/n_frames_jester.py ~/dataset/jester`
