### ISSUE TITLE
Modified THOP

### ISSUE THREAD

**Issue by rogercmq** [okankop/Efficient-3DCNNs#28]
Hi, thanks for your excellent work! I have cloned your repo and run ``calculate_FLOP.py``. It goes wrong. Here is my code:
```
import os
import torch
import torch.nn as nn
from thop import profile
from models import squeezenet, shufflenetv2, shufflenet, mobilenet, mobilenetv2, c3d, resnext, resnet

os.environ["CUDA_VISIBLE_DEVICES"] = "0,1,2,3"

model = c3d.get_model(num_classes=600, sample_size=112, sample_duration=16)
model = model.cuda()
model = nn.DataParallel(model, device_ids=[0,1])

pytorch_total_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print("Total number of trainable parameters: ", pytorch_total_params)

flops, prms = profile(model, input_size=(1, 3, 16, 112, 112))
print("Total number of FLOPs: ", flops)
``` 
which returns:
```
Total number of trainable parameters:  80459480
Traceback (most recent call last):
  File "calculate_FLOP.py", line 18, in <module>
    flops, prms = profile(model, input_size=(1, 3, 16, 112, 112))
  File "/home/caomengqi/Efficient-3DCNNs-master/thop/utils.py", line 54, in profile
    model(x)
  File "/home/caomengqi/anaconda3/envs/slowfast/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/caomengqi/anaconda3/envs/slowfast/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 155, in forward
    "them on device: {}".format(self.src_device_obj, t.device))
RuntimeError: module must have its parameters and buffers on device cuda:0 (device_ids[0]) but found one of them on device: cpu
```

So I am confused now. Could you please help me figure it out?

**Comment by okankop** [comment]
HI, Can you please try to calculate FLOPs without specifying the "CUDA_VISIBLE_DEVICES"? You can try the following code:
`
import torch.nn as nn
from thop import profile
from models import squeezenet, shufflenetv2, shufflenet, mobilenet, mobilenetv2, c3d, resnext, resnet

model = c3d.get_model( num_classes=600, sample_size=112, sample_duration=16)
model = model.cuda()
model = nn.DataParallel(model, device_ids=None)	

pytorch_total_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print("Total number of trainable parameters: ", pytorch_total_params)

flops, prms = profile(model, input_size=(1, 3, 16, 112, 112))
print("Total number of FLOPs: ", flops)
`

**Comment by rogercmq** [comment]
Hi, @okankop . Thanks for your quick reply. I just copied your code but it went wrong again.
Message:
```
Traceback (most recent call last):
  File "calculate_FLOP.py", line 12, in <module>
    flops, prms = profile(model, input_size=(1, 3, 16, 112, 112))
  File "/home/caomengqi/Efficient-3DCNNs-master/thop/utils.py", line 57, in profile
    model(input)
  File "/home/caomengqi/anaconda3/envs/slowfast/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/caomengqi/anaconda3/envs/slowfast/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 155, in forward
    "them on device: {}".format(self.src_device_obj, t.device))
RuntimeError: module must have its parameters and buffers on device cuda:0 (device_ids[0]) but found one of them on device: cpu
```
which is identical to what i mentioned in my last comment. 

My environment contains 4 GPUs and my PyTorch version is 1.7.1. 

Now I am working on your THOP and I will give you feedback ASAP.

Regards.

**Comment by rogercmq** [comment]
I feel so sorry to inform you that you can close this issue now

**Comment by rogercmq** [comment]
Sorry to update this issue right now. The CPU-version THOP works well. But I have difficulites in fine-tuning ResNet-50 on UCF101 (Split 1).  In my implementation, the video accuracy of my ResNet-50 is only 83% (88.92% in your paper). Could you give more details on hyperparams or data augmentation methods? 
Here is my current config:
```
--video_path Efficient-3DCNNs-master/UCF101/raw_frames \
--annotation_path Efficient-3DCNNs-master/annotation_UCF101/ucf101_01.json \
--result_path Efficient-3DCNNs-master/resnet50/ \
--pretrain_path Efficient-3DCNNs-master/pretrain/kinetics_resnet_50_RGB_16_best.pth \
--dataset ucf101 \
--n_classes 600 \
--n_finetune_classes 101 \
--ft_portion complete \
--model resnet \
--model_depth 50 \
--resnet_shortcut B \
--train_crop random \
--learning_rate 0.01 \
--sample_duration 16 \
--downsample 1 \
--batch_size 32 \
--n_threads 16 \
--checkpoint 1 \
--n_val_samples 1 \
--test \
--n_epochs 120 \
--lr_steps 30 60 90 \
``` 
Regards.

**Comment by Huixxi** [comment]
> HI, Can you please try to calculate FLOPs without specifying the "CUDA_VISIBLE_DEVICES"? You can try the following code:
> 
> ```
> import torch.nn as nn
> from thop import profile
> from models import squeezenet, shufflenetv2, shufflenet, mobilenet, mobilenetv2, c3d, resnext, resnet
> 
> model = c3d.get_model( num_classes=600, sample_size=112, sample_duration=16)
> model = model.cuda()
> model = nn.DataParallel(model, device_ids=None)	
> 
> pytorch_total_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
> print("Total number of trainable parameters: ", pytorch_total_params)
> 
> flops, prms = profile(model, input_size=(1, 3, 16, 112, 112))
> print("Total number of FLOPs: ", flops)
> ```

I just met the same error, even I used your own source code, I don't know why? Your model works well on Cuda when training, but it just raise the above error when I run the scripts to calculate the model flops.

**Comment by rogercmq** [comment]
@Huixxi You can modify those codes in the ``thop`` directory (see utils.py) , or you can simply deepcopy an CPU-based alternative model and calculate its FLOPs.
