### ISSUE TITLE
can’t calculate_FLOP

### ISSUE THREAD

**Issue by shxijack** [okankop/Efficient-3DCNNs#35]
i installed pytorch 1.4.
 when i instead c3d to resnet.resnet50,it say:"profile() got an unexpected keyword argument 'input_size'" .
i wanna calculate 3D model‘s flops.May i make a mistake at somewhere？

**Comment by okankop** [comment]
Hi @shxijack, could you please try re-cloning the repo. Because in the thop library profile function expects to take 'input_size' as input. You can check it out at [line25](https://github.com/okankop/Efficient-3DCNNs/blob/f8debe0db90d0b8a7590a3afe18cec0dc9eb3f4f/thop/utils.py#L25).
