### ISSUE TITLE
how to calculate the accuracy of the jester dataset

### ISSUE THREAD

**Issue by hanah-fei** [okankop/Efficient-3DCNNs#4]
Thanks for your nice work!
But I didn't figure out how to calculate the accuracy of the jester dataset, can you explain it?
Thanks a lot.

**Comment by okankop** [comment]
Average length of gestures in jester dataset is around 34. So, middle 32 frames of gestures are used with downsampling of 2 (taking every sexond frame) in order to calculate the video accuracy. I hope this explains your question.

**Comment by tkone2018** [comment]
@hanah-fei hello, did  you train the jester dataset successfully?
