### ISSUE TITLE
depthwise conv not supported 

### ISSUE THREAD

**Issue by Litou1** [okankop/Efficient-3DCNNs#9]
Hi, thanks for sharing your code. It looks amazing. 
But as far as I know, pytorch does not support depthwise convolution yet. 

https://github.com/pytorch/pytorch/issues/18631#issue-427166006

It is actually quite slow compared to standard conv.
Did you figure out a way to make it work?

**Comment by okankop** [comment]
Depthwise convolutions are not slow only for PyTorch, but also for other platforms like Tensorflow. It is a CUDNN problem since CUDNN is specialized for standard dense convolutions. So I guess we should wait untill someone builds a faster depthwise or group convolutions for CUDNN library.

**Comment by Litou1** [comment]
thank you!
